### PR TITLE
Updates to map.py

### PR DESCRIPTION
**Pull request by ianan**
Two changes to map.py

- One fixes the units in some of the header items that previously caused issues when trying to save to fits
- Added ability to apply x,y shift to the data before the map is made.

fyi, some conflicts between the commits on my fork and base - even though I sync'd my fork to the updated NuSTAR/nustar_pysolar before making my changes......

### CODE REVIEW

**Comment by bwgref** [comment]
@ianan Something looks like it went bad somewhere in the last PR on the master branch, because I see it as a commit rather than as a PR merge...maybe I did something silly.

Either way, what you've got above also has the commits for #55 and a bunch of stuff going back to 2018 in your PR. Looking at your master branch, you'e already committed these changes to your master, as well.

I think you need to revert your master to the current one on the origin, rebase your updates to that version, and then re-issue the PR.

I don't think I can do this for you on my end, but maybe @ayshih has an idea of how to fix this.

I would:
- Make a local copy somewhere else of the code updates you want to do
- Set the nustar fork as the 'upstream' repo for your master branch and then destructively revert to that commit.
- Reset the upstream for your master branch to your own GitHub repo and force push it there
- Rebase your map_shift branch to the new master branch (which should remove all of the conflicts)

Once that's cleanup is done, then I think we can look at this PR again.

**Comment by ianan** [comment]
Will try and see what happens....

**Comment by ayshih** [comment]
Here's one way to fix your current `master` branch.

If you haven't already set up the main repo as `upstream`:
```
git remote add upstream git://github.com/NuSTAR/nustar_pysolar
git fetch upstream
```

Then rebase your `master` branch locally:
```
git checkout master
git rebase upstream/master
```

Then push your local branch up to GitHub, and use `-f` to force it:
```
git push -f origin master
```

This PR will be automatically updated.

**Comment by ianan** [comment]
Thanks @ayshih - that seems to have fixed everything?

Now my fork just has my updated version of map.py and so just one commits ahead. So there are no conflicts now?

Someone should double check this.

**Comment by ayshih** [comment]
Yup, that fixed the commit history.  Don't add any more commits to your online `master` branch unless you want them to show up on this PR (prior to it being merged).

I haven't looked into the CI failure, but it doesn't look like it's related to your changes.

**Comment by ayshih** [comment]
> I haven't looked into the CI failure, but it doesn't look like it's related to your changes.

@bwgref The NumPy version is too old?  It looks like the CI is installing 1.11.3 (released December 2016).

**Comment by ayshih** [comment]
Oh, all versions in `.travis.yml` are ancient...

**Comment by bwgref** [comment]
@ayshih Yeah, I haven't touched that in forever. The CI failures are definitely deprications in numpy / other stuff. @ianan I think we can declare victory on this one and I can merge this PR in.

I don't *think* we've actually set up any actual test cases that would be affected by @ianan's update anyways. Once I do this merge I'll see if I can update the .travis.yml versions to something that actually works.

**Comment by bwgref** [comment]
@ianan In the future we might want to include documentation on what coordinate system is assumed for the X/Y shifts (e.g., what does a +X shift actually mean).

Also making the shifts unit-quantities self-aware would be good at some point (we already require Astropy, so we might as well us the units). I only expect the shifts to be in arcseconds, but we might as well make that explicit at some point.

**Pull request merged**
